from dataclasses import dataclass


@dataclass
class Challenges:
    assistStreakCount: int
    baronBuffGoldAdvantageOverThreshold: int
    controlWardTimeCoverageInRiverOrEnemyHalf: float
    earliestBaron: int
    earliestDragonTakedown: int
    earliestElderDragon: int
    earlyLaningPhaseGoldExpAdvantage: int
    fasterSupportQuestCompletion: int
    fastestLegendary: int
    hadAfkTeammate: int
    highestChampionDamage: int
    highestCrowdControlScore: int
    highestWardKills: int
    junglerKillsEarlyJungle: int
    killsOnLanersEarlyJungleAsJungler: int
    laningPhaseGoldExpAdvantage: int
    legendaryCount: int
    maxCsAdvantageOnLaneOpponent: float
    maxLevelLeadLaneOpponent: int
    mostWardsDestroyedOneSweeper: int
    mythicItemUsed: int
    playedChampSelectPosition: int
    soloTurretsLategame: int
    takedownsFirst25Minutes: int
    teleportTakedowns: int
    thirdInhibitorDestroyedTime: int
    threeWardsOneSweeperCount: int
    visionScoreAdvantageLaneOpponent: float
    InfernalScalePickup: int
    fistBumpParticipation: int
    voidMonsterKill: int
    abilityUses: int
    acesBefore15Minutes: int
    alliedJungleMonsterKills: float
    baronTakedowns: int
    blastConeOppositeOpponentCount: int
    bountyGold: int
    buffsStolen: int
    completeSupportQuestInTime: int
    controlWardsPlaced: int
    damagePerMinute: float
    damageTakenOnTeamPercentage: float
    dancedWithRiftHerald: int
    deathsByEnemyChamps: int
    dodgeSkillShotsSmallWindow: int
    doubleAces: int
    dragonTakedowns: int
    legendaryItemUsed: list[int]
    effectiveHealAndShielding: float
    elderDragonKillsWithOpposingSoul: int
    elderDragonMultikills: int
    enemyChampionImmobilizations: int
    enemyJungleMonsterKills: float
    epicMonsterKillsNearEnemyJungler: int
    epicMonsterKillsWithin30SecondsOfSpawn: int
    epicMonsterSteals: int
    epicMonsterStolenWithoutSmite: int
    firstTurretKilled: int
    firstTurretKilledTime: float
    flawlessAces: int
    fullTeamTakedown: int
    gameLength: float
    getTakedownsInAllLanesEarlyJungleAsLaner: int
    goldPerMinute: float
    hadOpenNexus: int
    immobilizeAndKillWithAlly: int
    initialBuffCount: int
    initialCrabCount: int
    jungleCsBefore10Minutes: float
    junglerTakedownsNearDamagedEpicMonster: int
    kda: float
    killAfterHiddenWithAlly: int
    killedChampTookFullTeamDamageSurvived: int
    killingSprees: int
    killParticipation: float
    killsNearEnemyTurret: int
    killsOnOtherLanesEarlyJungleAsLaner: int
    killsOnRecentlyHealedByAramPack: int
    killsUnderOwnTurret: int
    killsWithHelpFromEpicMonster: int
    knockEnemyIntoTeamAndKill: int
    kTurretsDestroyedBeforePlatesFall: int
    landSkillShotsEarlyGame: int
    laneMinionsFirst10Minutes: int
    lostAnInhibitor: int
    maxKillDeficit: int
    mejaisFullStackInTime: int
    moreEnemyJungleThanOpponent: float
    multiKillOneSpell: int
    multikills: int
    multikillsAfterAggressiveFlash: int
    multiTurretRiftHeraldCount: int
    outerTurretExecutesBefore10Minutes: int
    outnumberedKills: int
    outnumberedNexusKill: int
    perfectDragonSoulsTaken: int
    perfectGame: int
    pickKillWithAlly: int
    poroExplosions: int
    quickCleanse: int
    quickFirstTurret: int
    quickSoloKills: int
    riftHeraldTakedowns: int
    saveAllyFromDeath: int
    scuttleCrabKills: int
    shortestTimeToAceFromFirstTakedown: float
    skillshotsDodged: int
    skillshotsHit: int
    snowballsHit: int
    soloBaronKills: int
    SWARM_DefeatAatrox: int
    SWARM_DefeatBriar: int
    SWARM_DefeatMiniBosses: int
    SWARM_EvolveWeapon: int
    SWARM_Have3Passives: int
    SWARM_KillEnemy: int
    SWARM_PickupGold: float
    SWARM_ReachLevel50: int
    SWARM_Survive15Min: int
    SWARM_WinWith5EvolvedWeapons: int
    soloKills: int
    stealthWardsPlaced: int
    survivedSingleDigitHpCount: int
    survivedThreeImmobilizesInFight: int
    takedownOnFirstTurret: int
    takedowns: int
    takedownsAfterGainingLevelAdvantage: int
    takedownsBeforeJungleMinionSpawn: int
    takedownsFirstXMinutes: int
    takedownsInAlcove: int
    takedownsInEnemyFountain: int
    teamBaronKills: int
    teamDamagePercentage: float
    teamElderDragonKills: int
    teamRiftHeraldKills: int
    tookLargeDamageSurvived: int
    turretPlatesTaken: int
    turretsTakenWithRiftHerald: int
    turretTakedowns: int
    twentyMinionsIn3SecondsCount: int
    twoWardsOneSweeperCount: int
    unseenRecalls: int
    visionScorePerMinute: float
    wardsGuarded: int
    wardTakedowns: int
    wardTakedownsBefore20M: int
