from dataclasses import dataclass

from sqlalchemy import ForeignKey
from src.models.match.challenges import Challenges
from src.models.match.info import Info
from src.models.match.perks import Perks
from src.models.base import Base
from sqlalchemy.orm import Mapped, mapped_column, relationship


class Participant(Base):
    __tablename__ = "participant"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    info_id = Mapped[int] = mapped_column(ForeignKey("info.id"))
    info = Mapped[Info] = relationship(back_populates="participants")

    challenges_id: Mapped[int] = mapped_column(ForeignKey("challenges.id"))
    challenges: Mapped[Challenges] = relationship(uselist=False, back_populates="participant")

    allInPings: Mapped[int]
    assistMePings: Mapped[int]
    assists: Mapped[int]
    baronKills: Mapped[int]
    bountyLevel: Mapped[int]
    champExperience: Mapped[int]
    champLevel: Mapped[int]
    championId: Mapped[int]
    championName: Mapped[str]
    commandPings: Mapped[int]
    championTransform: Mapped[int]
    consumablesPurchased: Mapped[int]
    damageDealtToBuildings: Mapped[int]
    damageDealtToObjectives: Mapped[int]
    damageDealtToTurrets: Mapped[int]
    damageSelfMitigated: Mapped[int]
    deaths: Mapped[int]
    detectorWardsPlaced: Mapped[int]
    doubleKills: Mapped[int]
    dragonKills: Mapped[int]
    eligibleForProgression: Mapped[bool]
    enemyMissingPings: Mapped[int]
    enemyVisionPings: Mapped[int]
    firstBloodAssist: Mapped[bool]
    firstBloodKill: Mapped[bool]
    firstTowerAssist: Mapped[bool]
    firstTowerKill: Mapped[bool]
    gameEndedInEarlySurrender: Mapped[bool]
    gameEndedInSurrender: Mapped[bool]
    holdPings: Mapped[int]
    getBackPings: Mapped[int]
    goldEarned: Mapped[int]
    goldSpent: Mapped[int]
    individualPosition: Mapped[str]
    inhibitorKills: Mapped[int]
    inhibitorTakedowns: Mapped[int]
    inhibitorsLost: Mapped[int]
    item0: Mapped[int]
    item1: Mapped[int]
    item2: Mapped[int]
    item3: Mapped[int]
    item4: Mapped[int]
    item5: Mapped[int]
    item6: Mapped[int]
    itemsPurchased: Mapped[int]
    killingSprees: Mapped[int]
    kills: Mapped[int]
    lane: Mapped[str]
    largestCriticalStrike: Mapped[int]
    largestKillingSpree: Mapped[int]
    largestMultiKill: Mapped[int]
    longestTimeSpentLiving: Mapped[int]
    magicDamageDealt: Mapped[int]
    magicDamageDealtToChampions: Mapped[int]
    magicDamageTaken: Mapped[int]
    neutralMinionsKilled: Mapped[int]
    needVisionPings: Mapped[int]
    nexusKills: Mapped[int]
    nexusTakedowns: Mapped[int]
    nexusLost: Mapped[int]
    objectivesStolen: Mapped[int]
    objectivesStolenAssists: Mapped[int]
    onMyWayPings: Mapped[int]
    participantId: Mapped[int]
    playerScore0: Mapped[int]
    playerScore1: Mapped[int]
    playerScore2: Mapped[int]
    playerScore3: Mapped[int]
    playerScore4: Mapped[int]
    playerScore5: Mapped[int]
    playerScore6: Mapped[int]
    playerScore7: Mapped[int]
    playerScore8: Mapped[int]
    playerScore9: Mapped[int]
    playerScore10: Mapped[int]
    playerScore11: Mapped[int]
    pentaKills: Mapped[int]
    perks: Mapped[Perks]
    physicalDamageDealt: Mapped[int]
    physicalDamageDealtToChampions: Mapped[int]
    physicalDamageTaken: Mapped[int]
    placement: Mapped[int]
    playerAugment1: Mapped[int]
    playerAugment2: Mapped[int]
    playerAugment3: Mapped[int]
    playerAugment4: Mapped[int]
    playerSubteamId: Mapped[int]
    pushPings: Mapped[int]
    profileIcon: Mapped[int]
    puuid: Mapped[str]
    quadraKills: Mapped[int]
    riotIdGameName: Mapped[str]
    riotIdName: Mapped[str]
    riotIdTagline: Mapped[str]
    role: Mapped[str]
    sightWardsBoughtInGame: Mapped[int]
    spell1Casts: Mapped[int]
    spell2Casts: Mapped[int]
    spell3Casts: Mapped[int]
    spell4Casts: Mapped[int]
    subteamPlacement: Mapped[int]
    summoner1Casts: Mapped[int]
    summoner1Id: Mapped[int]
    summoner2Casts: Mapped[int]
    summoner2Id: Mapped[int]
    summonerId: Mapped[str]
    summonerLevel: Mapped[int]
    summonerName: Mapped[str]
    teamEarlySurrendered: Mapped[bool]
    teamId: Mapped[int]
    teamPosition: Mapped[str]
    timeCCingOthers: Mapped[int]
    timePlayed: Mapped[int]
    totalAllyJungleMinionsKilled: Mapped[int]
    totalDamageDealt: Mapped[int]
    totalDamageDealtToChampions: Mapped[int]
    totalDamageShieldedOnTeammates: Mapped[int]
    totalDamageTaken: Mapped[int]
    totalEnemyJungleMinionsKilled: Mapped[int]
    totalHeal: Mapped[int]
    totalHealsOnTeammates: Mapped[int]
    totalMinionsKilled: Mapped[int]
    totalTimeCCDealt: Mapped[int]
    totalTimeSpentDead: Mapped[int]
    totalUnitsHealed: Mapped[int]
    tripleKills: Mapped[int]
    trueDamageDealt: Mapped[int]
    trueDamageDealtToChampions: Mapped[int]
    trueDamageTaken: Mapped[int]
    turretKills: Mapped[int]
    turretTakedowns: Mapped[int]
    turretsLost: Mapped[int]
    unrealKills: Mapped[int]
    visionScore: Mapped[int]
    visionClearedPings: Mapped[int]
    visionWardsBoughtInGame: Mapped[int]
    wardsKilled: Mapped[int]
    wardsPlaced: Mapped[int]
    win: Mapped[bool]
