"""Hacer columnas tier y rank nullables en LeagueEntry

Revision ID: 2320d595eac3
Revises: 
Create Date: 2024-08-21 13:18:03.326257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2320d595eac3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_entry', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('league_entry', 'rank',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_entry', 'rank',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('league_entry', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
