"""Add ON DELETE CASCADE to Foreign Keys

Revision ID: 6132008c8c4c
Revises: 03b883fd3cc6
Create Date: 2024-08-22 16:14:31.587017

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6132008c8c4c'
down_revision: Union[str, None] = '03b883fd3cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('champion_stats_account_id_fkey', 'champion_stats', type_='foreignkey')
    op.create_foreign_key(None, 'champion_stats', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('league_entry_account_id_fkey', 'league_entry', type_='foreignkey')
    op.create_foreign_key(None, 'league_entry', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('match_account_id_fkey', 'match', type_='foreignkey')
    op.create_foreign_key(None, 'match', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('participant_match_id_fkey', 'participant', type_='foreignkey')
    op.create_foreign_key(None, 'participant', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.create_foreign_key('participant_match_id_fkey', 'participant', 'match', ['match_id'], ['id'])
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.create_foreign_key('match_account_id_fkey', 'match', 'account', ['account_id'], ['id'])
    op.drop_constraint(None, 'league_entry', type_='foreignkey')
    op.create_foreign_key('league_entry_account_id_fkey', 'league_entry', 'account', ['account_id'], ['id'])
    op.drop_constraint(None, 'champion_stats', type_='foreignkey')
    op.create_foreign_key('champion_stats_account_id_fkey', 'champion_stats', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###
