# Generated by Django 4.2.6 on 2023-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championstats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='last_update',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='championstats',
            unique_together={('name', 'summoner')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('puuid', 'match')},
        ),
    ]
