# Generated by Django 4.2.6 on 2023-12-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner_profile', '0002_match_team_id_alter_championstats_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_end',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_start',
            field=models.BigIntegerField(),
        ),
    ]
