# Generated by Django 4.2.6 on 2023-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner_profile', '0004_alter_championstats_assists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championstats',
            name='assists',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='championstats',
            name='deaths',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='championstats',
            name='kda',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='championstats',
            name='kills',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='championstats',
            name='minion_kills',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
